apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fisco
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fisco
  template: 
    metadata:
      labels:
        app: fisco
    spec:
      containers:
      - name: fisco
        image: 99kies/python_sdk
        imagePullPolicy: Never
#      dnsPolicy: Default
