apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: ctfd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ctfd
  template: 
    metadata:
      labels:
        app: ctfd
    spec:
      containers:
      - name: ctfd
        image: ctfd_ctfd
        imagePullPolicy: Never

